
export const CHANGE_CITY = 'CHANGE_CITY';

///AUTOCOMPLETE:
export const FETCH_AUTOCOMPLETE = 'FETCH_AUTOCOMPLETE';
export const FETCH_AUTOCOMPLETE_SUCCESS = 'FETCH_AUTOCOMPLETE_SUCCESS';
export const FETCH_AUTOCOMPLETE_ERROR = 'FETCH_AUTOCOMPLETE_ERROR';

//DAILY_WEATHER
export const FETCH_DAILY_WEATHER = 'FETCH_DAILY_WEATHER';
export const FETCH_DAILY_WEATHER_SUCCESS = 'FETCH_DAILY_WEATHER_SUCCESS';
export const FETCH_DAILY_WEATHER_ERROR = 'FETCH_DAILY_ERROR';

//WEEKLY_WEATHER
export const FETCH_WEEKLY_WEATHER = 'FETCH_WEEKLY_WEATHER';
export const FETCH_WEEKLY_WEATHER_SUCCESS = 'FETCH_WEEKLY_WEATHER_SUCCESS';
export const FETCH_WEEKLY_WEATHER_ERROR = 'FETCH_WEEKLY_WEATHER_ERROR';

